<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Administrator" failures="0" tests="15" name="testDAO.NguoiHocDAOTest" time="1.072" errors="3" timestamp="2020-06-30T14:54:19 GMT+07:00" skipped="0">
  <testcase classname="testDAO.NguoiHocDAOTest" name="selectByCourseNotFoundTest" time="0.002"/>
  <system-out/>
  <testcase classname="testDAO.NguoiHocDAOTest" name="updateWithEmptyModelTest" time="0.002">
    <error message="
Method NguoiHocDAOTest.updateWithEmptyModelTest()[pri:0, instance:testDAO.NguoiHocDAOTest@49a71302] should have thrown an exception of type class java.lang.Exception" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method NguoiHocDAOTest.updateWithEmptyModelTest()[pri:0, instance:testDAO.NguoiHocDAOTest@49a71302] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:741)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:629)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- updateWithEmptyModelTest -->
  <system-out/>
  <testcase classname="testDAO.NguoiHocDAOTest" name="deleteWithMaNhValidTest" time="0.004"/>
  <system-out/>
  <testcase classname="testDAO.NguoiHocDAOTest" name="insertWithNullModelTest" time="0.372"/>
  <system-out/>
  <testcase classname="testDAO.NguoiHocDAOTest" name="selectByKeywordTest" time="0.005"/>
  <system-out/>
  <testcase classname="testDAO.NguoiHocDAOTest" name="updateWithValidModelTest" time="0.002"/>
  <system-out/>
  <testcase classname="testDAO.NguoiHocDAOTest" name="deleteWithMaNhNullTest" time="0.019">
    <error message="
Method NguoiHocDAOTest.deleteWithMaNhNullTest()[pri:0, instance:testDAO.NguoiHocDAOTest@49a71302] should have thrown an exception of type class java.lang.Exception" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method NguoiHocDAOTest.deleteWithMaNhNullTest()[pri:0, instance:testDAO.NguoiHocDAOTest@49a71302] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:741)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:629)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- deleteWithMaNhNullTest -->
  <system-out/>
  <testcase classname="testDAO.NguoiHocDAOTest" name="insertWithValidModelTest" time="0.006"/>
  <system-out/>
  <testcase classname="testDAO.NguoiHocDAOTest" name="updateWithNullModelTest" time="0.002"/>
  <system-out/>
  <testcase classname="testDAO.NguoiHocDAOTest" name="selectTest" time="0.600"/>
  <system-out/>
  <testcase classname="testDAO.NguoiHocDAOTest" name="selectByCourseTest" time="0.016"/>
  <system-out/>
  <testcase classname="testDAO.NguoiHocDAOTest" name="findByIdWithNotFoundTest" time="0.028"/>
  <system-out/>
  <testcase classname="testDAO.NguoiHocDAOTest" name="selectByKeywordNotFoundTest" time="0.007"/>
  <system-out/>
  <testcase classname="testDAO.NguoiHocDAOTest" name="findByIdWithValidModelTest" time="0.004"/>
  <system-out/>
  <testcase classname="testDAO.NguoiHocDAOTest" name="insertWithEmptyModelTest" time="0.003">
    <error message="
Method NguoiHocDAOTest.insertWithEmptyModelTest()[pri:0, instance:testDAO.NguoiHocDAOTest@49a71302] should have thrown an exception of type class java.lang.Exception" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method NguoiHocDAOTest.insertWithEmptyModelTest()[pri:0, instance:testDAO.NguoiHocDAOTest@49a71302] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:741)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:629)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- insertWithEmptyModelTest -->
  <system-out/>
</testsuite> <!-- testDAO.NguoiHocDAOTest -->
